### PR TITLE
manually reassign clinic case to new VCPHCS providers

### PR DESCRIPTION
**Pull request by shuclu**

### CODE REVIEW

**Comment by binrai** [comment]
@shuclu 
From my testing, looks like adding this logic in the VW_EXTERNAL_ID_UPDATE might not get us the result we want. Below is my reasoning for that:

**Prior to this code, the following will have already happened:**
1. [`VW_EXTERNAL_ID_UPDATE`] The legacy clinics (XI and XII) get their external_id updated from legacy-external_id to bhe-external_id
2. [`VW_PROVIDER_CREAT_UPDATE`]  BHE providers (XI and XII) created.

**Concerns**: In this new code, the XI and XII clinics will not get captured because of the following [line of code](https://github.com/crassula-ovata/data_and_analytics_dbt_bha_ladders/pull/218/files#diff-20ce9ebd0ea18762c752fe4d4ed602b1c12c7ee5670a83d1a00880a266993f09R233) in the `clinic_case_update` cte 


 `
    inner join dm_table_data_clinic on legacy_clinic_external_id=dm_table_data_clinic.external_id_compare
 `

because the `external_id_compare`  will be the BHE-external_id and comparing it against the `legacy_clinic_external_id` will not match.

**Comment by binrai** [comment]
@shuclu  This manual mapping/reassignment of parent_case_id might work better in the VW_CLINICS_CREATE_UDPATE ??

**Comment by shuclu** [comment]
@binrai yeah, agree that changes in VW_CLINICS_CREATE_UDPATE is better, but at the same time, not too liking to make the temp changes there. 
would it be better now to ask bha team to make the parent re-assign manually?

**Comment by binrai** [comment]
@shuclu  Yes, let's plan to ask the Delivery team. I will reach out to them, and let them know.

**Pull request merged**
