### PR TITLE
Revert "Merge pull request #140 from crassula-ovata/br_ladders"

### PR DESCRIPTION
**Pull request by Joe-Mooney**
This reverts commit 589352e81d3b0060bcf7b91c032ec1d73d40b644, reversing changes made to 30f7bc363d71405898357f91c1d66f3ef0a34eb1.

### CODE REVIEW

**Comment by Joe-Mooney** [comment]
@binrai - Can you review this and let me know if it only reverts the exact changes you made so it will function like before we merged the PR?

**Comment by binrai** [comment]
@Joe-Mooney  Looks good

**Comment by Joe-Mooney** [comment]
@binrai - Can you approve the pull request?

**Review by binrai — APPROVED** [review]

**Comment by binrai** [comment]
@Joe-Mooney Sorry! It's approved now.

**Pull request merged**
